### ISSUE TITLE
Edit Permissions Dialog - errors in console and dialog does not close when 'Apply' button pressed

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#528]
`This bug does not reproduce when Edit Permissions Dialog was opened in Wizard`

1. Select a content in grid, open Details Panel, click on `Edit Permissions` link
2. change permissions, press the `Apply` button

Bug: 

![image](https://user-images.githubusercontent.com/3728712/47990015-79cfb700-e0f7-11e8-8591-e5efd469bdf1.png)

`_all.js:19536 Uncaught Error: Content type name can't be null
    at assert (http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1541407961/admin/common/js/_all.js:1:2390)
    at Object.assertNotNull (http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1541407961/admin/common/js/_all.js:1:2616)
    at new ContentTypeName (http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1541407961/admin/common/js/_all.js:1:1095464)
    at ApplyContentPermissionsRequest.JsonResourceRequest.fromJsonToContent (http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1541407961/js/bundle.js:1:222703)
    at http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1541407961/js/bundle.js:1:1555088
From previous event:
    at EditPermissionsDialog.applyPermissions (`

**Comment by alansemenov** [comment]
@sgauruseu this is caused by outdated [lib-admin-ui](http://repo.enonic.com/public/com/enonic/lib/lib-admin-ui/2.0.0-SNAPSHOT/) in the repo. doesn't reproduce locally.
