### ISSUE TITLE
Error in console when update or rollback a content with html-area 

### ISSUE THREAD

**Issue by sgauruseu** [enonic-archive/app-contentstudio-old#534]
**Case 1** :  **rollback a content with html-area** 

1. Select `Features` and open new `html-area` content
2. Type a name and save the content.
3. Type a text in the first area, save the content.
![image](https://user-images.githubusercontent.com/3728712/48060527-41021180-e1cd-11e8-8ab9-652e5718a942.png)

4. Open `Versions panel` and restore the previous  version

**Bug:** 

text is present in html-area, but the version without the text is restored

![image](https://user-images.githubusercontent.com/3728712/48060658-afdf6a80-e1cd-11e8-925d-c7af9346f1e4.png)

`typeError: Cannot read property 'getId' of undefined
    at HtmlArea.updateFormInputElValue (http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1541493994/js/bundle.js:1:871533)
    at HtmlArea.BaseInputTypeNotManagingAdd.updateInputOccurrenceElement (http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1541493994/admin/common/js/_all.js:1:989132)
    at InputOccurrenceView.update (http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1541493994/admin/common/js/_all.js:1:978941)
    at InputOccurrences.updateOccurrenceView (http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1541493994/admin/common/js/_all.js:1:975625)
    at http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1541493994/admin/common/js/_all.js:1:867121
    at http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1541493994/admin/common/js/_all.js:1:238232
    at Array.forEach (<anonymous>)
    at PropertyArray.forEach (http://localhost:8080/admin/tool/com.enonic.xp.app.contentstudio/main/_/asset/com.enonic.xp.app.contentstudio:1541493994/admin/common/js/_all.js:1:238199)
    at InputOccurrences.FormItemOccurrences.update `

**CASE 2:   Insert  a text-component and then insert an Image**

Step 1 :  Open SuperHero and insert new text-component

![image](https://user-images.githubusercontent.com/3728712/48068765-c3e29680-e1e4-11e8-913e-dc50f98adb0c.png)

Step 2: Insert an image in the component
Step 3: Click on Save button

![image](https://user-images.githubusercontent.com/3728712/48068854-f7252580-e1e4-11e8-8724-c1b77c916637.png)

**Comment by alansemenov** [comment]
Fixed [here ](https://github.com/enonic/app-contentstudio/commit/f36e35ebf3de5778c8df4cf341b858322f7af34e)
